/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  AP_Renesas                             */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX62N                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize su=0x100
#pragma stacksize si=0x300